
# Задание 3.1 - Сверточные нейронные сети (Convolutional Neural Networks)

Это последнее задание на numpy, вы до него дожили! Остался последний марш-бросок, дальше только PyTorch.  
В этом задании вы реализуете свою собственную сверточную нейронную сеть.

In [2]:
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

%load_ext autoreload
%autoreload 2

In [3]:
from dataset import load_svhn, random_split_train_val
from gradient_check import check_layer_gradient, check_layer_param_gradient, check_model_gradient
from layers import FullyConnectedLayer, ReLULayer, ConvolutionalLayer, MaxPoolingLayer, Flattener
from model import ConvNet
from trainer import Trainer, Dataset
from optim import SGD, MomentumSGD
from metrics import multiclass_accuracy

### Загружаем данные

На этот раз мы не будем их преобразовывать в один вектор, а оставим размерности `(num_samples, 32, 32, 3)`.

In [4]:
def prepare_for_neural_network(train_X, test_X):    
    train_X = train_X.astype(float) / 255.0
    test_X = test_X.astype(float) / 255.0
    
    # Subtract mean
    mean_image = np.mean(train_X, axis = 0)
    train_X -= mean_image
    test_X -= mean_image
    
    return train_X, test_X
    
train_X, train_y, test_X, test_y = load_svhn("data", max_train=10000, max_test=1000)    
train_X, test_X = prepare_for_neural_network(train_X, test_X)
# Split train into train and val
train_X, train_y, val_X, val_y = random_split_train_val(train_X, train_y, num_val = 1000)

### Реализуем новые слои!
Сначала основной новый слой - сверточный (Convolutional layer). Для начала мы реализуем его для только одного канала, а потом для нескольких.

Сверточный слой выполняет операцию свертки (convolution) с весами для каждого канала, а потом складывает результаты. Возможно, поможет пересмотреть Лекцию 6 или внимательно прочитать http://cs231n.github.io/convolutional-networks/

Один из подходов к реализации сверточного слоя основан на том, что для конкретного "пикселя" выхода применение сверточного слоя эквивалентно обычному полносвязному.

![Getting Started](conv_img.jpg)

Рассмотрим один такой "пиксель":

Он получает на вход  
регион входа I размера `(batch_size, filter_size, filter_size, input_channels)`,

применяет к нему веса W `(filter_size, filter_size, input_channels, output_channels` и выдает `(batch_size, output_channels)`.

Если:  
* вход преобразовать в I' `(batch_size, filter_size*filter_size*input_channels)`,  
* веса в W' `(filter_size*filter_size*input_channels, output_channels)`,

то выход "пикселе" будет эквивалентен полносвязному слою со входом I' и весами W'.  
Осталось выполнить его в цикле для каждого пикселя :)

In [5]:
# TODO: Implement ConvolutionaLayer that supports only 1 output and input channel

# Note: now you're working with images, so X is 4-dimensional tensor of
# (batch_size, height, width, channels)

np.random.seed(0)
X = np.array([
              [
               [[1.0], [2.0]],
               [[0.0], [-1.0]]
              ]
              ,
              [
               [[0.0], [1.0]],
               [[-2.0], [-1.0]]
              ]
             ])

# Batch of 2 images of dimensions 2x2 with a single channel
print("Shape of X:",X.shape)

layer = ConvolutionalLayer(in_channels=1, out_channels=1, filter_size=2, padding=0)
print("Shape of W", layer.W.value.shape)
layer.W.value = np.zeros_like(layer.W.value)
layer.W.value[0, 0, 0, 0] = 1.0
layer.B.value = np.ones_like(layer.B.value)
result = layer.forward(X)

assert result.shape == (2, 1, 1, 1)
assert np.all(result == X[:, :1, :1, :1] +1), "result: %s, X: %s" % (result, X[:, :1, :1, :1])


# Now let's implement multiple output channels
layer = ConvolutionalLayer(in_channels=1, out_channels=2, filter_size=2, padding=0)
result = layer.forward(X)
assert result.shape == (2, 1, 1, 2)


# And now multple input channels!
X = np.array([
              [
               [[1.0, 0.0], [2.0, 1.0]],
               [[0.0, -1.0], [-1.0, -2.0]]
              ]
              ,
              [
               [[0.0, 1.0], [1.0, -1.0]],
               [[-2.0, 2.0], [-1.0, 0.0]]
              ]
             ])

print("Shape of X:", X.shape)
layer = ConvolutionalLayer(in_channels=2, out_channels=2, filter_size=2, padding=0)
result = layer.forward(X)
assert result.shape == (2, 1, 1, 2)

Shape of X: (2, 2, 2, 1)
Shape of W (2, 2, 1, 1)
Shape of X: (2, 2, 2, 2)


### А теперь имплементируем обратный проход

Возможно, это самое сложное место в курсе. Дальше будет лучше.

Раз выполнение сверточного слоя эквивалентно полносвязному слою для каждого "пикселя" выхода, то общий обратный проход эквивалентен обратному проходу каждого из таких "слоев".  
Градиенты от каждого из этих "слоев" в каждом пикселе надо сложить в соответствующие пиксели градиента по входу, а градиенты весов сложить все вместе.

In [40]:
# First test - check the shape is right
layer = ConvolutionalLayer(in_channels=2, out_channels=2, filter_size=2, padding=0)
result = layer.forward(X)
d_input = layer.backward(np.ones_like(result))
assert d_input.shape == X.shape

# # Actually test the backward pass
# # As usual, you'll need to copy gradient check code from the previous assignment
layer = ConvolutionalLayer(in_channels=2, out_channels=2, filter_size=2, padding=0)
assert check_layer_gradient(layer, X)

layer = ConvolutionalLayer(in_channels=2, out_channels=2, filter_size=2, padding=0)
assert check_layer_param_gradient(layer, X, 'W')
layer = ConvolutionalLayer(in_channels=2, out_channels=2, filter_size=2, padding=0)
assert check_layer_param_gradient(layer, X, 'B')

CHECK GRADIENT
x is 
 [[[[ 1.  0.]
   [ 2.  1.]]

  [[ 0. -1.]
   [-1. -2.]]]


 [[[ 0.  1.]
   [ 1. -1.]]

  [[-2.  2.]
   [-1.  0.]]]]
analytic grad is 
 [[[[-1.2342309  -0.09028112]
   [-0.2320982  -0.97687821]]

  [[ 2.35547367  0.34562644]
   [ 0.74214092 -1.34064914]]]


 [[[-1.77790396 -1.86222897]
   [ 1.28985452 -0.07319631]]

  [[ 0.35319401 -0.98034809]
   [ 0.25882111  0.23274385]]]]
numeric grad array is 
 [[[[-1.2342309  -0.09028112]
   [-0.2320982  -0.97687821]]

  [[ 2.35547367  0.34562644]
   [ 0.74214092 -1.34064914]]]


 [[[-1.77790396 -1.86222897]
   [ 1.28985452 -0.07319631]]

  [[ 0.35319401 -0.98034809]
   [ 0.25882111  0.23274385]]]]
Gradient check passed!
CHECK GRADIENT
x is 
 [[[[ 0.09920486  1.57629897]
   [ 0.50232824 -0.862267  ]]

  [[ 0.16066119 -0.95264495]
   [ 1.60852216 -0.56157875]]]


 [[[ 0.20727075  0.30773257]
   [ 0.15925047 -1.95854896]]

  [[-1.44642106 -0.45235028]
   [ 0.31943183 -0.13777921]]]]
analytic grad is 
 [[[[-0.95714747 -1.34842432


Осталось реализовать дополнение нулями (padding).  
Достаточно дополнить входной тензор нулями по сторонам. Не забудьте учесть это при обратном проходе!

In [42]:
X = np.array([
              [
               [[1.0, 0.0], [2.0, 1.0]],
               [[0.0, -1.0], [-1.0, -2.0]]
              ]
              ,
              [
               [[0.0, 1.0], [1.0, -1.0]],
               [[-2.0, 2.0], [-1.0, 0.0]]
              ]
             ])
print("X shape ", X.shape)            
layer = ConvolutionalLayer(in_channels=2, out_channels=2, filter_size=3, padding=1)
result = layer.forward(X)
print("result shape is ", result.shape)
# Note this kind of layer produces the same dimensions as input
assert result.shape == X.shape,"Result shape: %s - Expected shape %s" % (result.shape, X.shape)
d_input = layer.backward(np.ones_like(result))
assert d_input.shape == X.shape
# layer = ConvolutionalLayer(in_channels=2, out_channels=2, filter_size=3, padding=1)
# assert check_layer_gradient(layer, X)

X shape  (2, 2, 2, 2)
result shape is  (2, 2, 2, 2)



### После следующего слоя вам уже будет все ни по чем - max pooling

Max Pooling - это слой, реализующий операцию максимума для каждого канала отдельно в окресности из pool_size "пикселей".

![Getting Started](max_pooling.jpg)

In [97]:
X = np.array([
              [
               [[1.0, 0.0], [2.0, 1.0]],
               [[0.0, -1.0], [-1.0, -2.0]]
              ]
              ,
              [
               [[0.0, 1.0], [1.0, -1.0]],
               [[-2.0, 2.0], [-1.0, 0.0]]
              ]
             ])
print("X shape ", X.shape) 


pool = MaxPoolingLayer(2, 2)
result = pool.forward(X)
assert result.shape == (2, 1, 1, 2)

assert check_layer_gradient(pool, X)

X shape  (2, 2, 2, 2)
CHECK GRADIENT
x is 
 [[[[ 1.  0.]
   [ 2.  1.]]

  [[ 0. -1.]
   [-1. -2.]]]


 [[[ 0.  1.]
   [ 1. -1.]]

  [[-2.  2.]
   [-1.  0.]]]]
analytic grad is 
 [[[[-1.00432271 -0.99819173]
   [ 0.          0.        ]]

  [[ 0.          0.        ]
   [ 0.          0.        ]]]


 [[[-1.37304255 -1.06774201]
   [ 0.          0.        ]]

  [[ 0.          0.        ]
   [ 0.          0.        ]]]]
numeric grad array is 
 [[[[-1.00432271 -0.99819173]
   [ 0.          0.        ]]

  [[ 0.          0.        ]
   [ 0.          0.        ]]]


 [[[-1.37304255 -1.06774201]
   [ 0.          0.        ]]

  [[ 0.          0.        ]
   [ 0.          0.        ]]]]
Gradient check passed!


In [94]:
X = np.array([
              [
               [[1.0, 1, 0.0], [2.0, 1, 1.0], [9.0, 1, 1.0]],
               [[0.0, 1,  -1.0], [-1.0, 1,  -2.0],[2.0, 1, 1.0]], 
               [[0.0, 1,  -1.0], [-5.0, 1,  -2.0],[2.0, 9, 1.0]],
               [[0.0, 1,  3.0], [13.0, 1,  -2.0],[2.0, 1, 1.0]]
              ]
              ,
              [
               [[0.0, 1, 1.0], [1.0, 1,  -1.0], [2.0, 1, 1.0]],
               [[-2.0, 1,  2.0], [-1.0, 1, 0.0], [2.0, 1, 1.0]],
               [[-2.0, 1,  2.0], [-1.0, 1, 0.0], [2.0, 1, 1.0]],
               [[0.0, 1,  -1.0], [-1.0, 22,  -2.0],[2.0, 1, 1.0]]
              ]
             ])

# A = np.array([[[3,3], [2,2]], [[3,3,], [1,1]]])
x_off= 1
y_off = 1
Y = X[:, x_off:2+x_off,  y_off:2 + y_off, :]
print("X shape is ", X.shape)
# print("Y shape is ", Y.shape)
# print(X)
# print(X.ndim)
# print("Y is\n", Y)
# print("A\n", A)
print("transformed X shape is ", X.T.shape)

b = [1000, 100, 30]
# print(X + b)
maxes = X.max(axis=(1, 2))
# indices = X.argmax(axis=(1, 2))
# indices = X.argmax(axis= (1,2))
x, y = np.argwhere(maxes==maxes.max())[0]
print(maxes)
print(x, y)
# print(maxes[ind[0], ind[1]])
# print(maxes.shape)


X shape is  (2, 4, 3, 3)
transformed X shape is  (3, 3, 4, 2)
[[13.  9.  3.]
 [ 2. 22.  2.]]
1 1
